{{- if eq (.Values.oidc.enabled | toString) "true" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spire.fullname" . }}-oidc-discovery-provider
  namespace: {{ .Release.Namespace }}
data:
  oidc-discovery-provider.conf: |
    log_level = "{{ .Values.oidc.logLevel }}"

    domain = "{{ .Values.oidc.domain }}"
    insecure_addr = ":{{ .Values.oidc.service.port }}"
    allow_insecure_scheme = {{ .Values.oidc.allowInsecureScheme }}
    acme {
        directory_url = "{{ .Values.oidc.acme.directoryUrl }}"
        cache_dir = "{{ .Values.oidc.acme.cacheDir }}"
        tos_accepted = {{ .Values.oidc.acme.tosAccepted }}
        email = "{{ .Values.oidc.acme.emailAddress }}"
    }
    workload_api {
        socket_path = "/run/spire/agent-sockets/agent.sock"
        trust_domain = "{{ .Values.spire.trustDomain }}"
    }
{{ end }}
