{{- if eq (.Values.oidc.enabled | toString) "true" }}
{{- $fullname := include "spire.fullname" . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-oidc" $fullname }}
  labels:
    {{- include "spire.oidc.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.oidc.replicaCount }}
  selector:
    matchLabels:
      {{- include "spire.oidc.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.oidc.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "spire.oidc.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- range . }}
        - name: {{ printf "%s-%s" $fullname .name }}
        {{- end }}
      {{- end }}
      serviceAccountName: {{ include "spire.serviceAccountName" . }}-agent
      securityContext:
        {{- toYaml .Values.oidc.podSecurityContext | nindent 8 }}
      initContainers:
        - name: pre-install-job
          image: "bitnami/kubectl:latest"
          command: ["cp /opt/csr/gen-cert.sh /tmp/gen-cert.sh && /tmp/gen-cert.sh", "{{ include "spire.fullname" . }}-oidc", "{{ .Release.Namespace }}"]
          volumeMounts:
            - name: spire-gen-cert
              mountPath: /opt/csr
      containers:
        - name: spire-oidc
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ template "spire.image" (dict "appVersion" $.Chart.AppVersion "image" .Values.oidc.image) }}
          imagePullPolicy: {{ .Values.oidc.image.pullPolicy }}
          args:
            - -config
            - /run/spire/oidc/config/oidc-discovery-provider.conf
          ports:
            - containerPort: 8008
              name: health
          {{- if not .Values.oidc.insecureScheme.enabled }}
            - containerPort: 443
              name: https
          {{- end }}
          volumeMounts:
            - name: spiffe-workload-api
              mountPath: /spiffe-workload-api
              readOnly: true
            - name: spire-oidc-sockets
              mountPath: /run/spire/oidc-sockets
              readOnly: false
            - name: spire-oidc-config
              mountPath: /run/spire/oidc/config/
              readOnly: true
          # Needs new release of spire to fix the http healthchecks
          # readinessProbe:
          #   httpGet:
          #     path: /ready
          #     port: health
          #   initialDelaySeconds: 5
          #   periodSeconds: 5
          # livenessProbe:
          #   httpGet:
          #     path: /live
          #     port: health
          #   initialDelaySeconds: 5
          #   periodSeconds: 5
          resources:
            {{- toYaml .Values.oidc.resources | nindent 12 }}
        {{- if .Values.oidc.insecureScheme.enabled }}
        - name: nginx
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ template "spire.image" .Values.oidc.insecureScheme.nginx }}
          imagePullPolicy: {{ .Values.oidc.insecureScheme.nginx.image.pullPolicy }}
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - name: spire-oidc-sockets
              mountPath: /run/spire/oidc-sockets
              readOnly: true
            - name: spire-oidc-config
              mountPath: /etc/nginx/templates/default.conf.template
              subPath: default.conf.template
            - name: oidc-ssl-certs
              mountPath: /etc/certs
              readOnly: true
      volumes:
        - name: spiffe-workload-api
          csi:
            driver: "csi.spiffe.io"
            readOnly: true
        - name: spire-oidc-sockets
          hostPath:
            path: /run/spire/oidc-sockets
            type: DirectoryOrCreate
        - name: spire-oidc-config
          configMap:
            name: {{ include "spire.fullname" . }}-oidc-discovery-provider
        - name: spire-gen-cert
          configMap:
            name: {{ include "spire.fullname" . }}-gen-cert
        - name: oidc-ssl-certs
          secret:
            secretName: {{ include "spire.fullname" . }}-oidc-ssl-certs
      {{- with .Values.oidc.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.oidc.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.oidc.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{ end }}
