apiVersion: v1
kind: Service
metadata:
  name: {{ include "spire.fullname" . }}-server
  namespace: {{ .Release.Namespace }}
  {{- with .Values.server.service.annotations }}
  annotations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  labels:
    {{- include "spire.server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - name: grpc
      port: {{ .Values.server.service.port }}
      targetPort: grpc
      protocol: TCP
  selector:
    {{- include "spire.server.selectorLabels" . | nindent 4 }}
