nameOverride: ""
fullnameOverride: ""

# subcharts
spire-server:
  nameOverride: server
  bundleConfigMap: &bundleConfigMap spire-bundle

  clusterName: &clusterName "example-cluster"
  trustDomain: &trustDomain "example.org"

spire-agent:
  nameOverride: agent
  bundleConfigMap: *bundleConfigMap

  clusterName: *clusterName
  trustDomain: *trustDomain

  socketPath: &agentSocketPath /run/spire/agent-sockets/spire-agent.sock

spiffe-csi-driver:
  agentSocketPath: *agentSocketPath

spiffe-oidc-discovery-provider:
  enabled: false
  trustDomain: *trustDomain
