nameOverride: ""
fullnameOverride: ""

# subcharts
spire-server:
  nameOverride: server
  bundleConfigMap: &bundleConfigMap spire-bundle

  clusterName: &clusterName "example-cluster"
  trustDomain: &trustDomain "example.org"

  socketPath: &serverSocketPath /run/spire/server-sockets/spire-server.sock

spire-agent:
  nameOverride: agent
  bundleConfigMap: *bundleConfigMap

  clusterName: *clusterName
  trustDomain: *trustDomain

  socketPath: &agentSocketPath /run/spire/agent-sockets/spire-agent.sock

spiffe-csi-driver:
  fullNameOverride: spiffe-csi-driver
  agentSocketPath: *agentSocketPath

spiffe-oidc-discovery-provider:
  fullNameOverride: spiffe-oidc-discovery-provider
  enabled: false
  trustDomain: *trustDomain

k8s-workload-registrar:
  fullNameOverride: k8s-workload-registrar
  enabled: true

  clusterName: *clusterName
  trustDomain: *trustDomain

  server:
    socketPath: *serverSocketPath
