name: Greetings

on: [issues, pull_request]

jobs:
  greeting:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/first-interaction@v1.1.1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for submitting your first issue. We will be looking into it as soon as possible.'
        pr-message: 'Thanks for your first PR. We really appreciate it!'
